### ISSUE TITLE
Connection refused to Spotify

### ISSUE THREAD

**Issue by eddiezane** [tma02/baritone#12]
Seems that something changed under the hood and it can't connect to the local instance.

```
Codez/baritone[master ☂ ] npm test

> Baritone@1.0.8 test /Users/eddiezane/Codez/baritone
> electron .

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
app is ready
waiting for spotify...
{ [Error: connect ECONNREFUSED 127.0.0.1:4370]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4370 }
{ [Error: socket hang up] code: 'ECONNRESET' }
connection failed; trying new port...
waiting for spotify...
{ [Error: connect ECONNREFUSED 127.0.0.1:4371]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4371 }
{ [Error: socket hang up] code: 'ECONNRESET' }
```

Appears another one of my projects is broken as well that controlled the client.

**Comment by tma02** [comment]
Spotify recently changed their WebHelper port range to 4380 to 4389, will be updating baritone soon.

**Comment by simonmetcalfe** [comment]
FWIW I tried updating the port in Baritone today but still could not get it to work.  Spotify web helper is definitely responding on 4380 and the client itself on 4381, but Baritone still fails to connect.  You can also see in the terminal the error is different for ports 4380 and 4381 when Spotify is running, we get an ECONNRESET instead of ECONNREFUSED, but I'm not sure what the problem is from hereon :(

waiting for spotify...
{ [Error: socket hang up] code: 'ECONNRESET' }
connection failed; trying new port...
waiting for spotify...
{ [Error: socket hang up] code: 'ECONNRESET' }
connection failed; trying new port...
waiting for spotify...
{ [Error: connect ECONNREFUSED 127.0.0.1:4382]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4382 }
{ [Error: socket hang up] code: 'ECONNRESET' }

**Comment by lxzap** [comment]
I'm new to GitHub and just downloaded the app.  It's not connecting for me either.  How can I uninstall the app?  Thanks.

**Comment by tma02** [comment]
This is probably the same issue that spotispy ran in to. I'll attempt the same fix I did for spotispy.
